server:
    port: 8000
debug: true
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: sys as sysdba
    password: admin@123
    driver-class-name: oracle.jdbc.OracleDriver


  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

